// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: format.proto

package live

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 视频格式类型
type FormatType int32

const (
	FormatType_UNKNOWN_FORMAT FormatType = 0
	FormatType_FLV            FormatType = 1
	FormatType_MP4            FormatType = 2
	FormatType_RTMP           FormatType = 3
	FormatType_RTC            FormatType = 4
	FormatType_HLS            FormatType = 5
)

// Enum value maps for FormatType.
var (
	FormatType_name = map[int32]string{
		0: "UNKNOWN_FORMAT",
		1: "FLV",
		2: "MP4",
		3: "RTMP",
		4: "RTC",
		5: "HLS",
	}
	FormatType_value = map[string]int32{
		"UNKNOWN_FORMAT": 0,
		"FLV":            1,
		"MP4":            2,
		"RTMP":           3,
		"RTC":            4,
		"HLS":            5,
	}
)

func (x FormatType) Enum() *FormatType {
	p := new(FormatType)
	*p = x
	return p
}

func (x FormatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormatType) Descriptor() protoreflect.EnumDescriptor {
	return file_format_proto_enumTypes[0].Descriptor()
}

func (FormatType) Type() protoreflect.EnumType {
	return &file_format_proto_enumTypes[0]
}

func (x FormatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormatType.Descriptor instead.
func (FormatType) EnumDescriptor() ([]byte, []int) {
	return file_format_proto_rawDescGZIP(), []int{0}
}

var File_format_proto protoreflect.FileDescriptor

var file_format_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6c, 0x69, 0x76, 0x65, 0x2a, 0x4e, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x46, 0x4f,
	0x52, 0x4d, 0x41, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x4c, 0x56, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x4d, 0x50, 0x34, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x54, 0x4d, 0x50,
	0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x54, 0x43, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x48,
	0x4c, 0x53, 0x10, 0x05, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6c, 0x69, 0x76, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_format_proto_rawDescOnce sync.Once
	file_format_proto_rawDescData = file_format_proto_rawDesc
)

func file_format_proto_rawDescGZIP() []byte {
	file_format_proto_rawDescOnce.Do(func() {
		file_format_proto_rawDescData = protoimpl.X.CompressGZIP(file_format_proto_rawDescData)
	})
	return file_format_proto_rawDescData
}

var file_format_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_format_proto_goTypes = []interface{}{
	(FormatType)(0), // 0: live.FormatType
}
var file_format_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_format_proto_init() }
func file_format_proto_init() {
	if File_format_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_format_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_format_proto_goTypes,
		DependencyIndexes: file_format_proto_depIdxs,
		EnumInfos:         file_format_proto_enumTypes,
	}.Build()
	File_format_proto = out.File
	file_format_proto_rawDesc = nil
	file_format_proto_goTypes = nil
	file_format_proto_depIdxs = nil
}
