// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: sdk.proto

package live

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// SDK类型
type SDK int32

const (
	// 未知类型
	SDK_UNKNOWN_SDK SDK = 0
	// 和直播
	SDK_AND_LIVE SDK = 1
	// 腾讯云直播
	SDK_TENCENTYUN SDK = 2
	// 创世云
	SDK_CHUANGCACHE SDK = 3
)

// Enum value maps for SDK.
var (
	SDK_name = map[int32]string{
		0: "UNKNOWN_SDK",
		1: "AND_LIVE",
		2: "TENCENTYUN",
		3: "CHUANGCACHE",
	}
	SDK_value = map[string]int32{
		"UNKNOWN_SDK": 0,
		"AND_LIVE":    1,
		"TENCENTYUN":  2,
		"CHUANGCACHE": 3,
	}
)

func (x SDK) Enum() *SDK {
	p := new(SDK)
	*p = x
	return p
}

func (x SDK) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SDK) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_proto_enumTypes[0].Descriptor()
}

func (SDK) Type() protoreflect.EnumType {
	return &file_sdk_proto_enumTypes[0]
}

func (x SDK) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SDK.Descriptor instead.
func (SDK) EnumDescriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{0}
}

var File_sdk_proto protoreflect.FileDescriptor

var file_sdk_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x69, 0x76,
	0x65, 0x2a, 0x45, 0x0a, 0x03, 0x53, 0x44, 0x4b, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x44, 0x4b, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x4e, 0x44,
	0x5f, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x45, 0x4e, 0x43, 0x45,
	0x4e, 0x54, 0x59, 0x55, 0x4e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x48, 0x55, 0x41, 0x4e,
	0x47, 0x43, 0x41, 0x43, 0x48, 0x45, 0x10, 0x03, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6c, 0x69,
	0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdk_proto_rawDescOnce sync.Once
	file_sdk_proto_rawDescData = file_sdk_proto_rawDesc
)

func file_sdk_proto_rawDescGZIP() []byte {
	file_sdk_proto_rawDescOnce.Do(func() {
		file_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdk_proto_rawDescData)
	})
	return file_sdk_proto_rawDescData
}

var file_sdk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_proto_goTypes = []interface{}{
	(SDK)(0), // 0: live.SDK
}
var file_sdk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_proto_init() }
func file_sdk_proto_init() {
	if File_sdk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdk_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_proto_goTypes,
		DependencyIndexes: file_sdk_proto_depIdxs,
		EnumInfos:         file_sdk_proto_enumTypes,
	}.Build()
	File_sdk_proto = out.File
	file_sdk_proto_rawDesc = nil
	file_sdk_proto_goTypes = nil
	file_sdk_proto_depIdxs = nil
}
