// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: stop.proto

package live

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 停止推流请求
type StopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编号
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StopReq) Reset() {
	*x = StopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReq) ProtoMessage() {}

func (x *StopReq) ProtoReflect() protoreflect.Message {
	mi := &file_stop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReq.ProtoReflect.Descriptor instead.
func (*StopReq) Descriptor() ([]byte, []int) {
	return file_stop_proto_rawDescGZIP(), []int{0}
}

func (x *StopReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 停止推流返回
type StopRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StopRsp) Reset() {
	*x = StopRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRsp) ProtoMessage() {}

func (x *StopRsp) ProtoReflect() protoreflect.Message {
	mi := &file_stop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRsp.ProtoReflect.Descriptor instead.
func (*StopRsp) Descriptor() ([]byte, []int) {
	return file_stop_proto_rawDescGZIP(), []int{1}
}

func (x *StopRsp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_stop_proto protoreflect.FileDescriptor

var file_stop_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x69,
	0x76, 0x65, 0x22, 0x19, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a,
	0x07, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x6c, 0x69, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stop_proto_rawDescOnce sync.Once
	file_stop_proto_rawDescData = file_stop_proto_rawDesc
)

func file_stop_proto_rawDescGZIP() []byte {
	file_stop_proto_rawDescOnce.Do(func() {
		file_stop_proto_rawDescData = protoimpl.X.CompressGZIP(file_stop_proto_rawDescData)
	})
	return file_stop_proto_rawDescData
}

var file_stop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stop_proto_goTypes = []interface{}{
	(*StopReq)(nil), // 0: live.StopReq
	(*StopRsp)(nil), // 1: live.StopRsp
}
var file_stop_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stop_proto_init() }
func file_stop_proto_init() {
	if File_stop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stop_proto_goTypes,
		DependencyIndexes: file_stop_proto_depIdxs,
		MessageInfos:      file_stop_proto_msgTypes,
	}.Build()
	File_stop_proto = out.File
	file_stop_proto_rawDesc = nil
	file_stop_proto_goTypes = nil
	file_stop_proto_depIdxs = nil
}
